// benchmarks/recursive-context/solid/src/App.jsx
import { createSignal, createContext, useContext } from 'solid-js';

// Balanced binary tree: depth D=10 → 1024 leaves, 2047 components.
//
// Two harness measurements:
//   __updateRoot()    — App's setRoot; signal write propagates fine-grained
//                       to all 1024 leaves that subscribed via root().
//   __updatePartial() — Mid's setLocal; only the 32 leaves inside the Mid
//                       subtree subscribed to LocalCtx via local(). Leaves
//                       outside the Mid subtree got the default getter
//                       (() => 0) which has no signal access, so they
//                       are never re-run.
//
// Idiom: place the signal GETTER in Context (not the scalar). Descendants
// invoke it inside JSX to subscribe.

const D = 10;
const M = 5;
const MID_PATH = 'L'.repeat(M);

// Default getters are non-reactive (no signal access) — non-Mid leaves invoke
// them and harmlessly get 0 without subscribing.
const RootCtx = createContext(() => 0);
const LocalCtx = createContext(() => 0);

let _setRoot = null;
let _setLocal = null;
export function bumpRoot() { if (_setRoot) _setRoot((v) => v + 1); }
export function bumpPartial() { if (_setLocal) _setLocal((v) => v + 1); }

function Mid(props) {
  const [local, setLocal] = createSignal(0);
  _setLocal = setLocal;
  // Solid 2.0: createContext() returns the provider FUNCTION directly —
  // no `.Provider` wrapper. <LocalCtx value={...}> IS the provider.
  return (
    <LocalCtx value={local}>
      <div class="mid">
        <Node depth={props.depth - 1} path={props.path + 'L'} />
        <Node depth={props.depth - 1} path={props.path + 'R'} />
      </div>
    </LocalCtx>
  );
}

function Node(props) {
  // Solid component bodies run ONCE; this ternary picks the right branch at
  // construction. props.depth/path never change after mount, so no need for
  // <Show> reactivity here.
  return props.depth > 0
    ? (props.path === MID_PATH
        ? <Mid depth={props.depth} path={props.path} />
        : (
          <div class="n">
            <Node depth={props.depth - 1} path={props.path + 'L'} />
            <Node depth={props.depth - 1} path={props.path + 'R'} />
          </div>
        ))
    : <Leaf path={props.path} />;
}

function Leaf(props) {
  const root = useContext(RootCtx);
  const local = useContext(LocalCtx);
  // root()/local() inside JSX create fine-grained subscriptions. The text
  // node updates surgically when either signal changes.
  return <span class="leaf">{props.path + '|' + root() + ':' + local()}</span>;
}

export default function App(props) {
  const [root, setRoot] = createSignal(0);
  _setRoot = setRoot;
  return (
    <RootCtx value={root}>
      <Node depth={props.depth} path={''} />
    </RootCtx>
  );
}

// benchmarks/recursive-context/react/src/App.jsx
import { createContext, useContext, useState, useEffect } from 'react';

// Balanced binary tree: depth D=10 → 1024 leaves, 2047 components.
//
// Two harness measurements:
//   __updateRoot()    — App's setState; React re-renders the entire tree.
//                       All 1024 leaves re-read the root context.
//   __updatePartial() — Mid's setState (mid-node at depth M=5); React
//                       re-renders Mid + descendants (32 leaves). Leaves
//                       outside the Mid subtree are NOT touched.

const D = 10;
const M = 5;
const MID_PATH = 'L'.repeat(M);

const RootCtx = createContext(0);
const LocalCtx = createContext(0);

// Module-level setter handles captured during render; only one App + one Mid
// exist so simple last-write-wins capture is fine.
let _setRoot = null;
let _setLocal = null;
export function bumpRoot() { if (_setRoot) _setRoot((v) => v + 1); }
export function bumpPartial() { if (_setLocal) _setLocal((v) => v + 1); }

function Mid({ depth, path }) {
  const [local, setLocal] = useState(0);
  _setLocal = setLocal;
  return (
    <LocalCtx.Provider value={local}>
      <div className="mid">
        <Node depth={depth - 1} path={path + 'L'} />
        <Node depth={depth - 1} path={path + 'R'} />
      </div>
    </LocalCtx.Provider>
  );
}

function Node({ depth, path }) {
  if (depth > 0) {
    if (path === MID_PATH) {
      return <Mid depth={depth} path={path} />;
    }
    return (
      <div className="n">
        <Node depth={depth - 1} path={path + 'L'} />
        <Node depth={depth - 1} path={path + 'R'} />
      </div>
    );
  }
  return <Leaf path={path} />;
}

function Leaf({ path }) {
  const root = useContext(RootCtx);
  const local = useContext(LocalCtx);
  return <span className="leaf">{path + '|' + root + ':' + local}</span>;
}

export default function App({ depth }) {
  const [root, setRoot] = useState(0);
  _setRoot = setRoot;
  return (
    <RootCtx.Provider value={root}>
      <Node depth={depth} path={''} />
    </RootCtx.Provider>
  );
}
